# Generated by Django 5.0.7 on 2024-07-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
